### ISSUE TITLE
[Bug] - Custom Installation page sample should use client.request, not ajax

### ISSUE THREAD

**Issue by satwikhebbar** [freshworks/marketplace-sample-apps#113]
- [ ] Look out for the app called `custom_installation_page_app` and navigate to `iparams.html` in it.
- [ ] You will quickly find out it is using the Ajax to make API call. Did you? Yet?
- [ ] Figure out what product the app is for by looking at `manifest.json`
- [ ] Search for that Freshworks' product's documentation and search for `Request API`or `Request Method` and understand it's usage. Then re-write the this ajax api call with Request API.
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product. We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com/)

**Comment by harish-sethuraman** [comment]
@Saif-Shines Can i pick this issue for hacktober fest ?

**Comment by Saif-Shines** [comment]
@harish-sethuraman 

Thanks for your interest. Sure, please feel free to pick this up. I will assign the PR to you.

**Comment by Saif-Shines** [comment]
@JANANI04 While multiple people picking up same issue for Hacktoberfest is not the problem, By the time of merging the pull request raised, maintainers can only merge 1 PR at a time. So even though multiple participants raise multiple PRs for the same issue, maintainers will have no choice to merge the best suitable one. (If there aren't any merge conflicts and legit, sometimes both)

If you find yourself feeling OK with this idea, then you can work on same issue. If not you can pick up another issue as well. :)

**Comment by harish-sethuraman** [comment]
@JANANI04 I have fixed the issue lll be creating a PR tomorrow. 
Thanks.
