### ISSUE TITLE
[App Request] - App to Appreciate FChat agent on resolving Conversation

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#125]
**Describe the sample app use-case :**
It would be an encouraging experience for Agents if FChat makes some encouraging statements whenever Agent resolves the conversation. 

- _You did a great job! **Agent Name** ._

- _**Customer Name** is a happy customer now!_

- _You have exchanged **Number of Messages** Messages with this customer! Kudos!_

- Fee free to think more add your own. At Least 10 such phrases.

**Demonstrated features**
This is a single app that will cover all the basic features of the platform for freshchat.
-  Use `conversation_background` to have the app running in the background.
- `Interface method` to show in product notification.
- `Data method` to substitute details inside notifications.
- `Events method` to show trigger js method when conversation is marked resolved

**Comment by harish-sethuraman** [comment]
Ill pick this App too ! @Saif-Shines

**Comment by Saif-Shines** [comment]
Sure @harish-sethuraman !

Please make sure you [signup for Hacktoberfest](https://hacktoberfest.digitalocean.com/details/) if you haven't yet! :)

**Comment by harish-sethuraman** [comment]
@Saif-Shines Yea sure ! i've done it.

**Comment by harish-sethuraman** [comment]
@Saif-Shines I have a small doubt. While showing the number of messages in the convo. Im using data method and fetching number of messages from the conversation object. It doesnt update when we send a new message and is updated only when we load a conversation. So shall i show the message count when the data was last fetched ?

**Comment by Saif-Shines** [comment]
@harish-sethuraman  That should be close enough. Maybe a pop saying "You have exchanged about **almost** XX number of messages with this customer! " will sound fair as well.

**Comment by harish-sethuraman** [comment]
@Saif-Shines Yep okay ive raised the pr.
