### ISSUE TITLE
[App Request] - Sync Airtable form submissions to Freshsales CRM 

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#127]
**Describe the sample app use-case :**
Imagine you are an Business Event collecting form submissions from the attendees at the Stall. It's highly likely that you may want to collect these leads and follow up via a CRM. This app lets you sync all the submissions as leads on Freshsales CRM every few intervals.

**Features Demonstrated**
- Serverless Feature - Scheduled Events to stick with time intervals.
- Interact with Freshsales API to create the Leads.
- [Advanced] Show the status of Leads created vs Leads yet to synced in `lead_details_page` placeholder.

**Do you already have a sample app / PR ready? :**
Yes/No

**More Hints :**
1. Each Airtable(_base_) has unique API endpoints. 
2. Have at least 5 Airtable form attributes.
3. Feel free to adjust schedule based on the rate limits set by Airtable. But should be justifiable.

**Comment by gopalak99** [comment]
Hi @Saif-Shines , regarding this Air table form sync app do you want it for both sales 360 and stand alone because sales360 does not have leads module.

**Comment by Saif-Shines** [comment]
@gopalak99 

This task might require more effort and time. Appreciate your effort to pick this issue. Let me enable this issue for Hacktoberfest and assign this issue to you.



> Air table form sync app do you want it for both sales 360 and stand alone because sales360 does not have leads module.

Only for sales would be very good enough. Please feel free to leave the app lean and minimum viable as per your time and flexibility.

**Comment by gopalak99** [comment]
@Saif-Shines 

Thanks for the clarification!
