### ISSUE TITLE
[App Request] - Collect leads from Google Ads

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#128]
**Describe the sample app use-case :**
Webhook enables you to send lead form data to your CRM system in real-time. Freshworks Developer Platform enables you to create a webhook and capture lead data and store it in Freshsales CRM

![image](https://user-images.githubusercontent.com/17451294/73173737-1383e980-412c-11ea-8c69-2210efd9f48c.png)

**More details :**
Please use [External Events](https://developers.freshsales.io/docs/external-events/#) platform feature and make API calls to freshsales. This features in Google Ads is still in beta version, please feel free to add comments if something doesn't work.

**Comment by Chris-Blesson** [comment]
Hello Saif, I would like to work on this could you assign this to me, thanks in advance. But can I use a sample data for this app?

**Comment by Saif-Shines** [comment]
Hi @Chris-Blesson ,

Yes, Chris. Since it's just the sample you can maybe put some Sample data alone!  Thank you for taking up interest, let me make this  availabe for Hacktoberfest.

**Comment by Chris-Blesson** [comment]
Thanks a lot @Saif-Shines

**Comment by Chris-Blesson** [comment]
Hey @Saif-Shines  I think there was some error while raising PR not sure if my PR got it in. Should I raise an another PR  ?

**Comment by Saif-Shines** [comment]
Looks it got in, @Chris-Blesson .
