### ISSUE TITLE
[Enhancement] - JS Doc commenting standards not followed

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#149]
_Maintainer's thoughts:_

This issue is ideally for pure beginners learning to make PRs and get familiar with open source contributions. Involve yourself to explore how apps on Freshworks developer platform run.

- [ ] Find sample code for `conditional ticket properties` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] (Optional) Add [summary in JSDoc commenting standards](https://jsdoc.app/tags-summary.html) and [elaborate parameters](https://jsdoc.app/tags-param.html) if you understand the code.
- [ ] Lower case the contents inside the `screenshots` folder (and `Screenshots` folder itself). If there's no screenshots just add it if it's a frontend app or else move on to next task. 
- [ ] Update the `README.md` file of the same app so that images inside of `screenshots` folder are displayed on the app README.md file.
- [ ] Re organise all the files and folders in following structure
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product. We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?

**Comment by itzarshath** [comment]
Is this issue specific to any app or to all app?

**Comment by Saif-Shines** [comment]
Hi @itzarshath ,

Couple of apps on this repository do not follow the JSDoc documenting standards, while anyone is allowed raise a PR fixing it for any app on this repository this issue by example suggests - `conditional ticket properties` app
