### ISSUE TITLE
[Bug] - ticket merger-loadDependency('needle');

### ISSUE THREAD

**Issue by WDOrahav** [freshworks/marketplace-sample-apps#158]
**Describe the bug**
receiving the following error when running the onTicketCreate event
server.js:836
var needle = (cov_21fw1getpg.s[0]++, loadDependency('needle'));
                                                       ^

ReferenceError: loadDependency is not defined
    at server.js:836:34
    at server.js:974:22
    at Script.runInContext (vm.js:133:20)
    at ProductEvent.sandboxExecutor (...\nvm\v10.18.0\node_modules\fdk\lib\event_handler\framework.js:223:25)
    at require (...\nvm\v10.18.0\node_modules\fdk\lib\event_handler\framework.js:110:27)
    at server.js:565:39
    at server.js:675:22
    at Script.runInContext (vm.js:133:20)
    at ProductEvent.sandboxExecutor (...\nvm\v10.18.0\node_modules\fdk\lib\event_handler\framework.js:223:25)
    at handler (...\nvm\v10.18.0\node_modules\fdk\lib\event_handler\framework.js:341:31)
server.js:836
var needle = (cov_21fw1getpg.s[0]++, loadDependency('needle'));

**Link to the bug'd Sample App**
[link](https://github.com/freshdesk/marketplace-sample-apps/tree/master/Demo-Apps/ticket_merger)

**To Reproduce**

- run fdk 

- Add api key in install 

- simulate onTicketCreateEvent at http://localhost:10001/web/test#

- See error in command line 

**Expected behavior**
Create a ticket, followed by a merge when a second ticket is created.

**Browser (please complete the following information):**
Chrome

**Additional context**

**Comment by Saif-Shines** [comment]
Thank you for proactively reporting the bug, @WDOrahav . Please expect the some delay in our response for few more days as we are working towards the [Freshworks Upskills Program](https://www.freshworks.com/platform/freshworks-upskill-program/). 

Meanwhile, I will follow your mentioned steps to reproduce the issue.

**Comment by RShalman** [comment]
Hi, @Saif-Shines !

The problem is that at line 1 in **servers.js** file you have `var needle = loadDependency('needle');`
and this `loadDependency` function is not declared or imported somewhere.
May be you somehow deleted it before?

**Comment by Saif-Shines** [comment]
@RShalman That could be the case. This is a very old app written 4 years ago. Let me look into and learn more about it to find good direction to fix this.
