### ISSUE TITLE
[Bug] - Dynamic iparams sample does not show error on first call

### ISSUE THREAD

**Issue by sabatale** [freshworks/marketplace-sample-apps#182]
**Describe the bug**
The UI shows an alert for an error status code only after a second attempt.

**Link to the bug'd Sample App**
[https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Configuration-Features/dynamic_iparams](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Configuration-Features/dynamic_iparams)

**To Reproduce**

1. See code below
2. Enter any value in field - returns error code 502 but no UI alert
3. Enter another value in the same field - returns error code 502 and gives UI alert

**Expected behavior**
The UI should show an error from the very first attempt.

**Screenshots**
![502_no](https://user-images.githubusercontent.com/50220345/92328036-159c1800-f02c-11ea-9017-47dd065e4649.gif)

**Browser (please complete the following information):**
Edge Chromium Latest build / Win 10 Pro

**Additional context**

Standard code from the sample:

**iparams.json**

```
{
  "twitter_id": {
    "display_name": "Twitter ID",
    "description": "Please enter your Acc. ID",
    "type": "text",
    "required": true,
    "events": [{
        "change": "checkAccountID"
    }]
}
}
```

**assets/iparams.js**

```
var timeout;

app.initialized().then(
  function (_client) {
    window.client = _client;
  },
  function (error) {
    //If unsuccessful
    console.error(error);
  }
);

function checkAccountID(newValue) {
  if (!isNaN(newValue)) {
    return Promise.reject("Account ID has to be a string");
  }

  return validateWithAPI(newValue);
}

function validateWithAPI(value) {
  var url = "https://httpstat.us/502";
  var options = {
    body: JSON.stringify({
      param: value,
    }),
  };
  var p = new Promise(function (resolve, reject) {
    clearTimeout(timeout);
    timeout = setTimeout(function () {
      client.request.post(url, options).then(
        function (data) {
          resolve();
        },
        function (error) {
          reject("This Account ID does not exist. Please enter the right one");
        }
      );
    }, 500);
  });
  return p;
}
```

**Comment by sabatale** [comment]
@hemchander23

**Comment by hemchander23** [comment]
Thanks for bringing this to our attention @sabatale. This issue has been reported and is being looked at. I will keep you updated on the progress

**Comment by hemchander23** [comment]
Hi @sabatale, The bug has been identified on the platform side and has been logged as a ticket. Will keep you posted on the fix

**Comment by Saif-Shines** [comment]
@sabatale Our team have notified us saying this issue has not been fixed ! Thanks for reporting the bug!
