### ISSUE TITLE
lowercase the folder name and update readme file

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#185]
_Maintainer's thoughts:_

This issue is ideally for pure beginners learning to make PRs and get familiar with open source contributions. Involve yourself to explore how apps on Freshworks developer platform run.

- [ ] Find sample code for `quick_links_app` app in this repository and tell us(in comments) if you were able to find it under 30s.
- [ ] Lower case the contents inside the `screenshots` folder (and `Screenshots` folder itself)
- [ ] Update the `README.md` file of the same app so that images inside of `screenshots` folder are displayed on the app README.md file.
- [ ] Re organise all the files and folders in following structure
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product. We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?

**Comment by rajatdiptabiswas** [comment]
Hi @Saif-Shines 
I have renamed the files to lowercase and updated references in the `README.md`.

I am having trouble understanding the file reorganization according to the folder tree you mentioned.
Should I change the structure of the contents of `/Demo-Apps/quick_links_app/app`?

This will break the links in the HTML files, right? I'm assuming the links should also be updated?
Should I rename the `template.html` to `index.html`?

**Comment by Saif-Shines** [comment]
Awesome, @rajatdiptabiswas !

To answer your questions,
- Yes,please only change the structure of contents of `quick_links_app`
- That will break the links. Your assumption is correct. Relevant places were they need to be update should be updated.
- Renaming `template.html` to `index.html` is the right move.

**Comment by ravirajsubramanian** [comment]
Hi @rajatdiptabiswas,

Thank you for picking up this task.

All the required changes are done. 🎉  I have suggested a small change in the file names of screenshot images.
Please incorporate the changes and let us know if you have any doubt on it.

**Comment by rajatdiptabiswas** [comment]
Hello @ravirajsubramanian 
I've made the changes. Please take a look at the new PR.
Thanks!

**Comment by ravirajsubramanian** [comment]
Awesome! 🎉

Thank you, @rajatdiptabiswas. 😄
