### ISSUE TITLE
make improvements to [advanced_data_storage_app]

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#186]
This app looks almost fine unless there are few updates to be done,

- [ ] Re organise all the files and folders in following structure. Make sure the `html`, `css` and `js` files have right references to `src`s.
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] If you find any `iparams_test_data.json` inside of `config/` directory. Delete it.
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product. We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com/)

**Comment by raj5036** [comment]
Working on this. Please assign me.

**Comment by raj5036** [comment]
I already have node and npm installed. Is installing nvm mandatory? Or I can proceed without that?

**Comment by ravirajsubramanian** [comment]
Hi @raj5036,

Thanks for showing interest to contribute.

NVM is not required. Currently, our CLI (FDK) works well with Node version 10.18. If you have other version, the app may not work very well. So, NVM can be used to install this version of Node additionally to work with Freshworks apps.

If you have the right version of Node, you're good to go. 😄

**Comment by raj5036** [comment]
Okay @ravirajsubramanian .

**Comment by harish-sethuraman** [comment]
@raj5036 Are you actively working on this issue or else i can fix this ?

**Comment by raj5036** [comment]
Okay go ahead... @harish-sethuraman
