### ISSUE TITLE
refactor [customer interactions app]

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#188]
All I would disclose here is this app is uses data store of the Freshworks developer platform. Yet, there are a lot of things that you have help this app be a code sample for rest of the developer community. I will quickly list out some of those steps.
- [ ] Find sample code for `conditional ticket properties` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] (Optional) Add [summary in JSDoc commenting standards](https://jsdoc.app/tags-summary.html) and [elaborate parameters](https://jsdoc.app/tags-param.html) if you understand the code.
- [ ] Update the `README.md` file so that it follows [the standard format](https://github.com/freshworks/marketplace-sample-apps/blob/master/.github/PULL_REQUEST_TEMPLATE/APP_README_TEMPLATE.md). Don't worry about filling in all the details. Just give it a shot.
- [ ] If you find any `iparams_test_data.json` inside of `config/` directory. Delete it.
- [ ] Re organise all the files and folders in following structure. Make sure the `html`, `css` and `js` files have right references to `src`s.
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product (*Hint*: See `manifest.json`). We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Take a look at Data Storage section of developer documentation to understand it's usage
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com/)

**Comment by mani-rsg** [comment]
Can you assign this to me @Saif-Shines ?
