### ISSUE TITLE
reorganise [request_api] app

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#189]
This app simply demostrates the usage of Request API that app uses. However there are some problems those need to fixed for the broader developer community to benefit while using this code sample.
- [ ] Find sample code for `request_api` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] If you find any `iparams_test_data.json` inside of `config/` directory. Delete it.
- [ ] Re organise all the files and folders in following structure. Make sure the `html`, `css` and `js` files have right references to `src`s.
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] (Optional) Add [summary in JSDoc commenting standards](https://jsdoc.app/tags-summary.html) and [elaborate parameters](https://jsdoc.app/tags-param.html) if you understand the code.
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product (*Hint*: See `manifest.json`). We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Take a look at Request API section of developer documentation

**Comment by harish-sethuraman** [comment]
@Saif-Shines Ill pick this issue ! 😃

**Comment by Saif-Shines** [comment]
Assigned it to you @harish-sethuraman !
