### ISSUE TITLE
reorganise [custom installation page] app

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#194]
_Maintainer's thoughts:_

This issue is ideally for pure beginners learning to make PRs and get familiar with open source contributions. Involve yourself to explore how apps on Freshworks developer platform run. You may not end up develop apps for Freshworks but experiece remains helpful where so ever you choose to build apps. Chrome Store? Web Apps? Atlassian apps? Using github CLI? Stripe CLI?

- [ ] Find sample code for `custom installation page` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] Update the `README.md` file so that it follows [the standard format](https://github.com/freshworks/marketplace-sample-apps/blob/master/.github/PULL_REQUEST_TEMPLATE/APP_README_TEMPLATE.md). Don't worry about filling in all the details. Just give it a shot.
- [ ] Rename `template.html` to `index.html`. Former is weird, isn't it?
- [ ] If you find any `iparams_test_data.json` inside of `config/` directory. Delete it.
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product (*Hint*: See `manifest.json`). We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com/)

**Comment by harish-sethuraman** [comment]
@Saif-Shines  Ill take up this issue 😄
