### ISSUE TITLE
organise [sample_full_page_app]

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#195]
_Maintainer's thoughts:_

This issue is ideally for pure beginners learning to make PRs and get familiar with open source contributions. Involve yourself to explore how apps on Freshworks developer platform run. You may not end up develop apps for Freshworks but experiece remains helpful where so ever you choose to build apps. Chrome Store? Web Apps? Atlassian apps? Using github CLI? Stripe CLI?

- [ ] Find sample code for `sample full page app` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] (Optional) Add [summary in JSDoc commenting standards](https://jsdoc.app/tags-summary.html) and [elaborate parameters](https://jsdoc.app/tags-param.html) if you understand the code.
- [ ] Update the `README.md` file so that it follows [the standard format](https://github.com/freshworks/marketplace-sample-apps/blob/master/.github/PULL_REQUEST_TEMPLATE/APP_README_TEMPLATE.md). Don't worry about filling in all the details. Just give it a shot.
- [ ] Rename `template.html` to `index.html`. Former is weird, isn't it?
- [ ] If you find any `iparams_test_data.json` inside of `config/` directory. Delete it.
- [ ] Re organise all the files and folders in following structure. Make sure the `html`, `css` and `js` files have right references to `src`s.
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/what-are-the-prerequisites-to-install-the-freshworks-cli/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product (*Hint*: See `manifest.json`). We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Take a look at <Interface API> section of developer documentation
- [ ] Files inside of `config/` folder are helpful for the app to collect configuration details that may be required for the app to run. Mostly it would be a `.json` or `.html` file. 
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com/)

**Comment by itzarshath** [comment]
Can this be assigned to me? Thanks.

**Comment by Saif-Shines** [comment]
Thank you taking tome on this, @itzarshath !

**Comment by ravirajsubramanian** [comment]
> Can this be assigned to me? Thanks.

@ghost do you need any help with this?

**Comment by sauravjaiswalsj** [comment]
Can this be assigned to me?
 Thanks

**Comment by ravirajsubramanian** [comment]
> Can this be assigned to me?
> Thanks

Sure, Saurav.
Please approach [our developer community](community.developers.freshworks.com) if you need any help.

**Comment by sauravjaiswalsj** [comment]
I have created PR #289 Please check

**Comment by ravirajsubramanian** [comment]
Thank you @sauravjaiswalsj for your contribution!

If you have any feedback, please let us know in [our developer community](https://community.developers.freshworks.com).
