### ISSUE TITLE
[App Request] -  Typescript Serverless App sample

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#199]
**Describe the sample app use-case :**
There are a lot of app [developers](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/Freshchat) who might be looking to build a Typescript serverless app. How about coming up with a template for developer community for it?

**For which product ? :**
- [ ] Freshdesk
- [x] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller

Feel free to extend the functionality and use-case as feasible to you for the sample app template.

**Comment by HunainHumail** [comment]
Can I make a serverless chat app on firebase using React Native?

**Comment by Saif-Shines** [comment]
@HunainHumail 

Sure you can. Let me have an issue created for it ans assign it to you.

Appreciate your interest.

**Comment by Saif-Shines** [comment]
@HunainHumail 

Do you mind creating an issue for it on this repository and describe how you want to build it? (Select 'Blank issue template' if existing templates do not fit well )

I will let some of our team members to engage with you on a thread and we could solution it in optimal way. Once you feel more confident, may be you can start working on the PR.

**Comment by arunrajkumar235** [comment]
Linking this to a PR https://github.com/freshworks/marketplace-sample-apps/pull/214
