### ISSUE TITLE
[Enhancement] - Refactor custom installation page app

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#200]
_Maintainer's thoughts:_

This issue is ideally for pure beginners learning to make PRs and get familiar with open source contributions. Involve yourself to explore how apps on Freshworks developer platform run. You may not end up develop apps for Freshworks but experience remains helpful where so ever you choose to build apps. Chrome Store? Web Apps? Atlassian apps? Using GitHub CLI? Stripe CLI?

- [ ] Find sample code for `custom installation page` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] Let's de-clutter the `config/iparams.html` file by isolating the style into a separate CSS file and scripts into a separate JS file and move those inside `config/assets` directory to import them again in the `config/iparams.html`. This is the core part of this issue. 😃
- [ ] Install [Freshworks CLI](https://community.developers.freshworks.com/t/234)
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product (*Hint*: See `manifest.json`). We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com). How much time did you take to figure out? 2 min?
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com)

**Comment by iyosayi** [comment]
Can this be assigned to me? Thanks.

**Comment by ravirajsubramanian** [comment]
Hi @iyosayi,

Sure, I will assign this to you.

Please post in the comments here if you have any queries.

**Comment by iyosayi** [comment]
Thank you, if I have any queries, I'd let you know.
