### ISSUE TITLE
[Enhancement] - Add secure installation parameter in the simple request app

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#201]
### Description of the enhancement
In the [simple_request_app](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Advanced-Features/request_method/simple_request_app) for Request method, sample HTTP request methods are shown with the use of [Request API feature](https://developer.freshdesk.com/v2/docs/request-api).
Secure installation parameter is not showcased in this app.

### Suggested solution
Change the URL from hard-coded string to piping it from a [installation parameter](https://developer.freshdesk.com/v2/docs/installation-parameters).
Mark this parameter as a secure parameter and use a template string in the Request API to use it.

**Comment by itzarshath** [comment]
Can this be assigned to me? Thanks

**Comment by Saif-Shines** [comment]
Assigned, @itzarshath :)
