### ISSUE TITLE
Refactor ticket close interceptor's Javascript code

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#207]
This issue more on code improvement focus. If you find this exciting, feel free to pick it up.

1. Somewhere on this repository, there's an Freshdesk app named `ticket_close_interceptor`
2. Once you find it, look into app.js code in it. It might look bit longer with callback hell.
3. Look at this [example of HTML, CSS and JS code](https://jsbin.com/kafepeh/3/edit?html,css,js) and make existing code for app.js more readable.

You would ideally be expected to learn about platform's [Events API to intercept the events](https://developers.freshdesk.com/v2/docs/events-api/#).

**Comment by RShalman** [comment]
I'll take it)

**Comment by RShalman** [comment]
Created PR #210
