### ISSUE TITLE
Refactor [timer_on_tap] app

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#216]
- [ ] Find sample code for ~~`conditional ticket properties`~~ `timer_on_tap` app in the repository and tell us(in comments) if you were able to find it under 30s.
- [ ] (Optional) Add [summary in JSDoc commenting standards](https://jsdoc.app/tags-summary.html) and [elaborate parameters](https://jsdoc.app/tags-param.html) if you understand the code.
- [ ] Lower case the contents inside the `screenshots` folder (and `Screenshots` folder itself). If there's no screenshots just add it if it's a frontend app or else move on to next task. 
- [ ] Update the `README.md` file so that it follows [the standard format](https://github.com/freshworks/marketplace-sample-apps/blob/master/.github/PULL_REQUEST_TEMPLATE/APP_README_TEMPLATE.md). Don't worry about filling in all the details. Just give it a shot.
- [ ] If you find any `iparams_test_data.json` inside of `config/` directory. Delete it.
- [ ] We have standard Javascript within browser now able to handle a lot of DOM events. Look for js files under `app/` folder and see if you can eliminate the use of JQuery. [`Hint`:[Use JQuery to JS Cheatsheet](https://tobiasahlin.com/blog/move-from-jquery-to-vanilla-javascript/#document-ready)]
 - [ ] Look at this [example of HTML, CSS and JS code](https://jsbin.com/kafepeh/3/edit?html,css,js)
- [ ] Re organise all the files and folders in following structure. Make sure the `html`, `css` and `js` files have right references to `src`s.
```
    .
    ├── README.md                   A file for future self and friends to learn about app
    ├── app                         A folder to place files needed for app's frontend components
    │   ├── index.html              The Entry point for the user to use the app
    │   ├── scripts                 JavaScript to handle frontend components business logic
    │   │   └── app.js
    │   ├── styles                  A folder to place all the styles for the app
    │   │   ├── images              A folder for all the images
    │   │   │   └── icon.svg
    │   │   └── styles.css
    │   └── views                   A folder to place all the pages
    │       └── modal.html
    ├── config                      A folder to place configuration pages
    │   └── iparams.json            A JSON oriented way to construct a configuration page
    └── manifest.json               A JSON file holding meta data for app to run on platform

```
- [ ] Locally run the app by getting a trial account for relevant Freshworks' product (*Hint*: See `manifest.json`). We will let you figure out how to do that by exploring the [developer documentation](https://developers.freshworks.com/). How much time did you take to figure out? 2 min?
- [ ] Take a look at Interface API and Placeholders section of developer documentation
- [ ] Files inside of `config/` folder are helpful for the app to collect configuration details that may be required for the app to run. Mostly it would be a `.json` or `.html` file. 
- [ ] Facing difficulties? Reference to this issue and create a topic in [developer community](https://community.developers.freshworks.com/)

**Comment by SoldierCorp** [comment]
Hi!

I found the sample code in about 40s because to be honest, I didn't know where to look at first so I cloned the repo and performed a search.

But I would like to help if you can assign it to me please.

**Comment by Saif-Shines** [comment]
Sure, @SoldierCorp 

I wanted to acknowledge that I made a mistake initially in the first task in the issue description which I've fixed it now.

40s! Cool, thanks for being honest. We hoping for the app to be discoverable under 1 min as well

**Comment by Saif-Shines** [comment]
@SoldierCorp , Do let us know if you need any help :-)

**Comment by SoldierCorp** [comment]
Hi @Saif-Shines,

I already replaced jQuery for plain JS in `startTimer.js` but I have the following questions and I hope you can help me to solve them.

- Even before the replacing, the app in my ticket on the Freshdesk dashboard wasn't working because I am getting this `Some error has occured while fetching Agents.` every time I press on `time_on_tap` and the error on catch is returning this. 
![image](https://user-images.githubusercontent.com/1775881/96976537-98483c00-14e1-11eb-9043-38d3f44bd481.png)

I already re-organised all the files and folders according to the folder structure you wrote down but when I run `fdk run`, I got these errors.
![image](https://user-images.githubusercontent.com/1775881/96978945-9338bc00-14e4-11eb-97f9-4b2bd4c0e413.png)

And of course, is because of the new folder structure but I updated the paths in the manifest to the new locations, and still not working.

**Comment by ravirajsubramanian** [comment]
@SoldierCorp The issue says the URL sent in the Request API is an invalid URL. If you take a look at the API request code, you can notice there's a template `https://<%= iparam.freshdesk_domain %>.freshdesk.com` where `freshdesk_domain` is expected to come from [iparam (Installation Parameter)](https://developer.freshdesk.com/v2/docs/installation-parameters).

Follow the testing steps to fill in the installation parameters before running the app. That should solve this issue.
If it's still not resolved, please post it on [our developer forum](community.developers.freshworks.com) to discuss with our community.

**Comment by SoldierCorp** [comment]
@ravirajsubramanian 

I did it, the terminal displayed the instruction to open http://localhost:10001/custom_configs and fill the form and I filled it so I'll check the forum this time.

Thanks!

**Comment by ravirajsubramanian** [comment]
The jQuery library has been removed from this app on #245. So, it can be neglected when addressing this issue.
