### ISSUE TITLE
[Enhancement] - Convert ES6 syntax to ES5 syntax

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#229]
**Description of the enhancement:**
In the [advanced_data_storage_app](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app), change all the ES6 syntax to ES5 syntax to support wide range of browsers and older browser versions.

**For which Freshworks product?**
- [x] [Freshdesk](https://developer.freshdesk.com/v2/docs/quick-start)
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller
- [ ] Freshteam

**Comment by AlexandreInsua** [comment]
Can I work in this issue?

**Comment by ravirajsubramanian** [comment]
> Can I work in this issue?

@AlexandreInsua, this issue was addressed in #231. Can you pick up any other issues to give a PR?

**Comment by AlexandreInsua** [comment]
@ravirajsubramanian, I'm afraid there are already people working on all issues.

**Comment by ravirajsubramanian** [comment]
@AlexandreInsua Hey, Hope, you're doing well.
I have added a few more issues. Please take a look at them if they are interesting to give a PR for. 😀
