### ISSUE TITLE
[Enhancement] - Remove jQuery imports from apps that never uses it

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#234]
**Description of the enhancement:**
The following apps do not use jQuery. But, it was imported in the HTML files of the application.
1. Demo-Apps/react_todo_app
2. Demo-Apps/sentimental_jeff_app
3. Demo-Apps/twilio_sms
4. Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/advanced_data_storage_app
5. Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/customer_interactions_app
6. Freshworks-Samples/App-Development-Features/Advanced-Features/data_storage/data_storage_ sample_demo
7. Freshworks-Samples/App-Development-Features/Advanced-Features/instance_method/instance_api_app
8. Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/asana_serverless_oauth_app
9. Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/authentication_basic
10. Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/freshsales_oauth_app
11. Freshworks-Samples/App-Development-Features/Advanced-Features/oauth2/shopify_oauth_app
12. Freshworks-Samples/App-Development-Features/Basic-Features/events_method/event_api
13. Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app
14. Freshworks-Samples/App-Development-Features/Basic-Features/events_method/intercepting_events_app_2
15. Freshworks-Samples/App-Development-Features/Basic-Features/events_method/simple_events_api_app
16. Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/interface_api
17. Freshworks-Samples/App-Development-Features/Basic-Features/interface_method/ticket_background_app
18. Freshworks-Samples/App-Development-Features/Configuration-Features/custom_installation_page_app
19. Freshworks-Samples/App-Development-Features/Configuration-Features/dynamic_iparams
20. Freshworks-Samples/App-Development-Features/Configuration-Features/iparam_api
21. Freshworks-Samples/App-Development-Features/Configuration-Features/sample_full_page_app
22. Freshworks-Samples/App-Development-Features/Configuration-Features/sample_secure_api_app
23. Freshworks-Samples/App-Development-Features/crayons/Github_Issue_Creator
24. Freshworks-Samples/App-Development-Features/crayons/Ticket_creator
25. Freshworks-Samples/App-Development-Features/crayons/ticket_details_freshservice_app
26. Freshworks-Samples/App-Development-Features/Serverless-Features/scheduled_events/scheduled_event_one_time
27. Freshworks-Samples/App-Development-Features/Serverless-Features/server_method_invocation
28. Freshworks-Samples/Freshcaller/ticket_fetcher
29. Freshworks-Samples/Freshchat/agent-appreciation-app
30. Freshworks-Samples/Freshchat/conversations-data-storage-app
31. Freshworks-Samples/Freshchat/mailchimp
32. Freshworks-Samples/Freshchat/statuspage
33. Freshworks-Samples/Freshchat/voucher
34. Freshworks-Samples/Freshdesk/sample_cti_app
35. Freshworks-Samples/Freshdesk/simple-fd-req-app
36. Freshworks-Samples/Freshdesk/ticket_property_hider
37. Freshworks-Samples/Freshdesk/ticket_tag_checker
38. Freshworks-Samples/Freshdesk/tickets_close_interceptor
39. Freshworks-Samples/Freshdesk/simple_request_app
40. Freshworks-Samples/Freshsales/ui_style_guide
41. Freshworks-Samples/Freshservice/freshdesk_app_for_freshservice
42. Freshworks-Samples/Freshservice/freshservice-caching
43. Freshworks-Samples/Freshservice/freshservice_app_for_freshdesk
44. Freshworks-Samples/Omni-App-Samples/Custom-Installation-Page_Omni
45. Freshworks-Samples/Omni-App-Samples/Data-Method_Omni
46. Freshworks-Samples/Omni-App-Samples/iparams-json-omni-app
47. Play-Along/Exercises/fundamentals/level1
48. Play-Along/Exercises/fundamentals/level2
49. Play-Along/Exercises/fundamentals/level3
50. Play-Along/Freshworks-Huddle/August-2020/freshdesk-sdk
51. Play-Along/Freshworks-Huddle/August-2020/ Freshteam-frontend
52. Play-Along/Tutorials/sample_full_page_app
53. Play-Along/Tutorials/sample_jwt_app

**Describe the solution you'd like**
Remove the unnecessary import of jQuery library from the HTML files of these listed applications

**Comment by carlospatinos** [comment]
Can I take this?

**Comment by ravirajsubramanian** [comment]
Hi @carlospatinos,

Thanks for taking this app. Looks like some of these apps use jQuery in the scripts as well.

If they are using jQuery, please try to replace it's usage with VanillaJS scripts. (You can use [this jQuery to JS cheatsheet](https://tobiasahlin.com/blog/move-from-jquery-to-vanilla-javascript/#document-ready) if it's helpful) or just leave those apps out of your PR.
I will create separate issues for those apps.

**Comment by sauravjaiswalsj** [comment]
Can this be assigned to me?
Thanks

**Comment by ravirajsubramanian** [comment]
@sauravjaiswalsj Sorry, it has already been fixed in #285, #286, and #287. I will update the status of this issue.
