### ISSUE TITLE
[Enhancement] - Remove jQuery from quick_links_app app

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#236]
**Description of the enhancement:**
The jQuery library has been imported and used in the `Demo-Apps/quick_links_app` app. Since jQuery is a heavy-lift for this simple application and jQuery is not safe-by-default, it can be removed altogether and replaced with Vanilla JavaScript and CSS wherever it is used.

**For which Freshworks product?**
- [x] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [ ] Freshservice
- [ ] Freshcaller
- [ ] Freshteam

**Describe the solution you'd like**
- [ ] Remove jQuery imports from HTML file
- [ ] Replace jQuery with Vanilla JavaScript and CSS

**Comment by JoaoJesus94** [comment]
Hello, I would like to help on this one. Can you assign it to me?

**Comment by ravirajsubramanian** [comment]
Hi @JoaoJesus94,
Sure, I will assign this to you. We hope to get a PR from you soon. 😀
