### ISSUE TITLE
[Enhancement] - Remove jQuery from onclick_alerts app

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#248]
**Description of the enhancement:**
The jQuery library has been imported and used in the `Freshworks-Samples/Freshservice/onclick_alerts` app. Since jQuery is a heavy-lift for this simple application and jQuery is not safe-by-default, it can be removed altogether and replaced with Vanilla JavaScript and CSS wherever it is used.

**For which Freshworks product?**
- [ ] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [x] Freshservice
- [ ] Freshcaller
- [ ] Freshteam

**Describe the solution you'd like**
- [ ] Remove jQuery imports from HTML file
- [ ] Replace jQuery with Vanilla JavaScript and CSS

**Comment by ethanny2** [comment]
Hello, can I attempt to fix this issue? I ran it locally in the recommended dev environment and it seems like within `Freshworks-Samples/Freshservice/onclick_alerts/app/app.js` this snippet when the document is ready


```
    $(document).ready(function() {
        app.initialized().then(initAPP);
    });
```


actually fires twice probably registering the same eventListeners. This is most likely a problem beyond the scope of this issue, but I just thought I would bring it up.

**Comment by ravirajsubramanian** [comment]
Hey @ethanny2,

If you're already working on this issue, let me assign it to you.

About the first issue, check if you can fix it while you're refactoring the code. If it's still occurring, please create an issue so that anyone else can pick it up and fix it.

About the coverage, yes, it's fine for the PR to have less coverage.
