### ISSUE TITLE
[Enhancement] - Remove jQuery from show_ticket_and_associated_details app

### ISSUE THREAD

**Issue by ravirajsubramanian** [freshworks/marketplace-sample-apps#249]
**Description of the enhancement:**
The jQuery library has been imported and used in the `Freshworks-Samples/Freshservice/show_ticket_and_associated_details` app. Since jQuery is a heavy-lift for this simple application and jQuery is not safe-by-default, it can be removed altogether and replaced with Vanilla JavaScript and CSS wherever it is used.

**For which Freshworks product?**
- [ ] Freshdesk
- [ ] Freshchat
- [ ] Freshsales
- [x] Freshservice
- [ ] Freshcaller
- [ ] Freshteam

**Describe the solution you'd like**
- [ ] Remove jQuery imports from HTML file
- [ ] Replace jQuery with Vanilla JavaScript and CSS

**Comment by svnnynior** [comment]
Hello, I would like to take this over, could you assign it to me?

**Comment by Chris-Blesson** [comment]
Hello @ravirajsubramanian ill work on this.

**Comment by ravirajsubramanian** [comment]
Sure, @Chris-Blesson. I have assigned it to you. Hope to see a PR from you soon. 😃

**Comment by ravirajsubramanian** [comment]
This issue has been resolved in PR #287
