### ISSUE TITLE
[App Request] - config-placeholders-freshservice

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#299]
We are trying to build an app repository for every app developer can always refer to and trust by when reusing it. We are working on a [project](https://github.com/freshworks/marketplace-sample-apps/projects/4) for which we would really appreciate if you become part of it.

This repository requires an app similar to **[config-placeholders-freshdesk](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshdesk)** for [Freshservice](https://developers.freshservice.com/docs/app-locations/).

- [x] Simalar [Readme](https://github.com/freshworks/marketplace-sample-apps/blob/master/Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshdesk/README.md) file with screenshots and description
- [x] Covers all the placeholders
- [x] Must follow the same or better code pattern than [similar freshdesk equivalent](https://github.com/freshworks/marketplace-sample-apps/tree/master/Freshworks-Samples/App-Development-Features/Configuration-Features/config-placeholders-freshdesk)
- [x] Must be in the `Freshworks-Samples/App-Development-Features/Configuration-Features/` directory

**Comment by teja-kummarikuntla** [comment]
@Saif-Shines , I think we can close this issue, the required app was added during PR #311
