### ISSUE TITLE
[Bug] - freshhuddle.github.io no longer valid

### ISSUE THREAD

**Issue by Saif-Shines** [freshworks/marketplace-sample-apps#306]
In the `Play Along/Exercises/README.md` it appears to suggest users refer to freshhuddle.github.io which is no longer valid.

**Comment by yashsehgal** [comment]
Hey @Saif-Shines, I have gone through the URL and understood the issue. Do we need to remove that link or replace it with any other link?

**Comment by Saif-Shines** [comment]
Yes, @yashsehgal 

We will need to replace the same with the following link (non-existent at the time of issue creation) - https://developers.freshworks.com/tutorials/

_Appreciate you jumping in_

**Comment by yashsehgal** [comment]
Thanks, @Saif-Shines for your quick help. I would love to fix this bug

**Comment by Saif-Shines** [comment]
Sure, @yashsehgal 

Looking forward for your PR
