### ISSUE TITLE
[Bug] - how to refresh the accesstoken of freshdesk oauth app. 

### ISSUE THREAD

**Issue by AnithaYerra** [freshworks/marketplace-sample-apps#356]
Hi @raghuram-periaswamy ,
I have built one oauth app. if am leaving for some time as idle am getting : Response 210 “Accesstoken can’t be refreshed so may i know how can i refresh the accesstoken inside the freshdesk authconfig.json

**Comment by teja-kummarikuntla** [comment]
Hey @AnithaYerra,
You can get this issue addressed in our developer community forum at: https://community.developers.freshworks.com
Feel free to create Topics, make discussions and get a good push when you get stuck.

**Comment by AnithaYerra** [comment]
Hi @teja-kummarikuntla , 
I have already raised there too. Thanks for the update- https://community.developers.freshworks.com/t/getting-accesstoken-can-t-be-refreshed-as-an-output-in-freshdesk-oauth-app/3620

**Comment by ravirajsubramanian** [comment]
Hi @AnithaYerra,

This repository only serves as example code. Let's continue the conversation in the forum topic. I have now responded to your query.
