### ISSUE TITLE
[Bug] - Crash Android FLAG_IMMUTABLE android 12

### ISSUE THREAD

**Issue by tspoke** [freshworks/marketplace-sample-apps#360]
**Describe the bug**
On android 12 when receiving a notification the call to consume() make the app crash

**To Reproduce**
1. Send a message with freshchat web admin
2. Consume it on Android with any version of your SDK
3. CRASH

**Additional context**
You need to implement the new FLAG_IMMUTABLE when using PendingIntent : https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent

**Comment by ravirajsubramanian** [comment]
Hi @tspoke,

This repository serves as sample applications built on Freshworks Developer Platform to publish apps on the Freshworks Marketplace.
Please report your issue on [Freshchat support page](https://support.freshchat.com/support/home).

**Comment by tspoke** [comment]
Hi @ravirajsubramanian,

I know, sorry for that but I wrote to the support and they didn't understand. Here I was sure to talk to a developer ;)

**Comment by ravirajsubramanian** [comment]
Ah got it. Please ask the support agent to redirect the issue to Freshchat mobile engineering team and convey it's an issue report on Freshchat Andriod SDK. They will be able to redirect to a development team who can understand your bug report and confirm if it's a bug or provide alternatives if available.

Could you share the ticket link here so I can try redirecting internally?

Thank you for taking the effort to report a bug.

**Comment by tspoke** [comment]
I contacted them on Facebook, and for now the agent didn't understand the issue :D 
So I don't have an open ticket, but I think you can forward this github issue directly ? Thanks a lot !
