### ISSUE TITLE
How to call API without adding domain name in whitelisted

### ISSUE THREAD

**Issue by ankurhiteshi** [freshworks/marketplace-sample-apps#366]
I have worked on level1 project in Play-Along/Exercises/fundamentals/level1
If the user enters a domain other than the whitelisted domain, then he will get the issue again. Is there another way to handle dynamic domain names?

**Comment by ravirajsubramanian** [comment]
@ankurhiteshi  You can check out [this repository](https://github.com/freshworks-developers/community-hours-demos/tree/main/iparams/custom-iparams-page) as an example for a dynamic definition of `whitelisted-domains` to automatically use the installation parameters.

Please use [our Freshworks Developer Community](https://community.developers.freshworks.com/) to discuss any issues or to continue your query.
